### PR TITLE
fix: reduce bundle size

### PR DESCRIPTION
**Pull request by hugomrdias**
revert readable-stream to 2 
require pull-stream specific fns
update deps
remove unused ci files

### CODE REVIEW

**Comment by hugomrdias** [comment]
@jacobheun can you review this PR and take into consideration this https://github.com/libp2p/js-libp2p-mplex/pull/87/files?utf8=%E2%9C%93&diff=split&w=1

**Comment by hugomrdias** [comment]
test only fail on macos browser which is probably machine related

**Comment by jacobheun** [comment]
It looks like libp2p tests are passing, but libp2p-switch is failing with this branch. Can you take a look at those?

**Comment by hugomrdias** [comment]
@jacobheun we should probably close this and move on to libp2p right?

**Comment by jacobheun** [comment]
> @jacobheun we should probably close this and move on to libp2p right?

Yes, with the upcoming move to `pull-mplex` this won't be needed. We can revisit the bundle-size when this package moves to async iterator support (node streams).

**Pull request closed without merging**
