### PR TITLE
fix!: upgrade to interface-stream-muxer 2.0.0

### LINKED ISSUE #185: Incompatible with interface-stream-muxer 2.0.0: needs closer
The upgrade from 1.0.2 to 2.0.0 for interface-stream-muxer is incompatible:

```
Type 'Mplex' is not assignable to type 'StreamMuxerFactory'.
  Property 'close' is missing in type 
    22     close: (err?: Error) => void;
```

### PR DESCRIPTION
**Pull request by paralin**
Adds the close() function to the StreamMuxer interface.

Fixes #185

### CODE REVIEW

**Comment by wemeetagain** [comment]
Can you update the interface-stream-muxer-compliance-tests too? should indicate a few more things need to be tweaked.

**Comment by wemeetagain** [comment]
I think we'll need to add something like the changes to the mock muxer here: https://github.com/libp2p/js-libp2p-interfaces/pull/254/files

Specifically the adding the closeController, using it to abort the sink, checking the whether its closed or not in `newStream`, and deduplicating logic from source.onEnd

**Comment by achingbrain** [comment]
> the stream muxer compliance tests didn't get released

Groan. I think it's because `semantic-release-monorepo` [doesn't update sibling deps](https://github.com/pmowrer/semantic-release-monorepo/issues/29) during a release so if a major bump occurs siblings end up depending on the old version even though they are coded against the newer one.

Maybe this is something we can handle in aegir.

**Comment by achingbrain** [comment]
@paralin the stream muxer compliance tests have been released, please can you update this PR to pull in the latest version?

**Pull request merged**
